# Filter AMR papers with LLM

Use the `llm.py` helper to ask a model whether a paper's abstract asserts that a pathogen is showing **significant resistance** to a given antibiotic.

In [1]:

# --- LLM filtering configuration ---
import pandas as pd

from llm import create_llm_client
from amr.filtering import (
    DEFAULT_SYSTEM_PROMPT,
    prepare_pmids_to_review,
    run_llm_filter,
)

SYSTEM_PROMPT = """
You are an expert microbiologist reviewing evidence. Given a title and abstract, decide whether the authors explicitly state or conclude that the specified pathogen is showing clinically meaningful resistance to the specified antibiotic.

Rules:
- Answer "yes" only if the abstract clearly reports resistance, reduced susceptibility, treatment failure due to resistance, or emergence of resistant isolates for that pathogen/antibiotic pair.
- Answer "no" if the abstract does not make that claim, is about a different organism/drug, only mentions testing without resistance, or only provides background.
- Answer "uncertain" if the abstract is missing, ambiguous, or only indirectly related.
- Base the decision only on the provided text; do not infer beyond it.

Return compact JSON with keys: decision (yes/no/uncertain) and rationale (one short sentence).
"""

LLM_PROVIDER = "openai"
MODEL_NAME = "gpt-4o-mini"
NCBI_EMAIL = "your_email@example.com"
N_PMIDS_PER_RUN = 1000  # how many unprocessed PMIDs to handle this run
RATE_LIMIT = 0.35  # seconds between PubMed calls
OUTPUT_PATH = "pmids_results_filtered.parquet"
LOG_PATH = "pmid_filter.log"
MAX_LLM_CALLS = None  # set to an integer to cap spend per run
DRY_RUN = False  # set True to skip LLM calls
SAVE_EVERY = 50  # checkpoint frequency

llm_kwargs = {}
if MODEL_NAME:
    llm_kwargs["model"] = MODEL_NAME

llm = create_llm_client(provider=LLM_PROVIDER, **llm_kwargs)
print(f"Using provider={LLM_PROVIDER}, model={MODEL_NAME or 'provider default'}; dry_run={DRY_RUN}; max_llm_calls={MAX_LLM_CALLS}")

Using provider=openai, model=gpt-4o-mini; dry_run=False; max_llm_calls=None

In [2]:
#!pip install openai requests pandas lxml

In [3]:

import os
import pandas as pd
from amr.filtering import prepare_pmids_to_review

# Load previous decisions
if os.path.exists(OUTPUT_PATH):
    reviewed_df = pd.read_parquet(OUTPUT_PATH)
    reviewed = set(reviewed_df['pmid'].astype(str)) if not reviewed_df.empty else set()
    print(f"Resuming with {len(reviewed)} PMIDs already reviewed from {OUTPUT_PATH}")
else:
    reviewed_df = None
    reviewed = set()

pmid_df = pd.read_parquet("pmids_results.parquet")
# Build full exploded table to report totals
full_long_df = prepare_pmids_to_review(pmid_df, exclude_pmids=None)
full_total = len(full_long_df)

# Exclude reviewed first, THEN cap to the next chunk
long_df = full_long_df
if reviewed:
    long_df = long_df[~long_df['pmid'].astype(str).isin(reviewed)]

pmid_total = len(long_df)
reviewed_count = len(reviewed)
print(f"Total PMIDs in source (exploded): {full_total}")
print(f"Loaded {pmid_total} candidate PMIDs after exclusion; reviewed set size: {reviewed_count}")

if N_PMIDS_PER_RUN:
    long_df = long_df.head(N_PMIDS_PER_RUN)

if len(long_df) == 0:
    print("No PMIDs remain after excluding reviewed. Consider using a fresh OUTPUT_PATH or adding more source data.")

print(f"PMIDs remaining to review this run: {len(long_df)}")
long_df.head()

Resuming with 8448 PMIDs already reviewed from pmids_results_filtered.parquet
Total PMIDs in source (exploded): 518057
Loaded 430266 candidate PMIDs after exclusion; reviewed set size: 8448
PMIDs remaining to review this run: 1000

           pmid                 pathogen  antibiotic  start_date    end_date
15271  25932248  Acinetobacter baumannii  Gentamicin  2015/01/01  2019/12/31
15272  25860039  Acinetobacter baumannii  Gentamicin  2015/01/01  2019/12/31
15274  25599131  Acinetobacter baumannii  Gentamicin  2015/01/01  2019/12/31
15276  25543268  Acinetobacter baumannii  Gentamicin  2015/01/01  2019/12/31
15277  24827985  Acinetobacter baumannii  Gentamicin  2015/01/01  2019/12/31

# How decisions are derived

Each PMID is fetched and passed to the LLM with a precise prompt:

- Target pathogen and antibiotic are specified as “exact match only”.
- The LLM is instructed to decide if the authors explicitly state clinically meaningful resistance of THIS pathogen to THIS antibiotic.
- It must choose one of three decisions and return JSON.

# Decision meanings

**yes:** The abstract clearly reports resistance or reduced susceptibility for the specified pathogen/antibiotic pair—e.g., treatment failure due to resistance, emergence of resistant isolates, MICs showing resistance, or wording that unambiguously claims resistance for that pair.

**no:** The abstract does not make that claim for the specified pair. This includes:

- The study is about a different organism or drug.
- It mentions testing without reporting resistance for the target pair.
- It only provides background or context without asserting resistance for the target pair.

**uncertain:** Used when the evidence is insufficient or unusable:

- Missing or empty abstract.
- Ambiguous wording that doesn’t clearly assert or deny resistance for the target pair.
- Indirectly related content (e.g., adjacent species/drugs, surveillance without explicit resistance claim).
- LLM parsing/response failures or dry-run mode.

# Behavior in the pipeline

- PMIDs with no abstract are recorded as uncertain with rationale “no abstract”.
- LLM call failures are recorded as uncertain with a failure rationale.
- Dry runs mark entries as uncertain with rationale “dry_run”.
- Only PMIDs already present in the reviewed parquet are skipped entirely; all others get a decision recorded.

In [4]:
%%time
filtered_df = run_llm_filter(
    long_df,
    llm,
    email=NCBI_EMAIL,
    rate_limit=RATE_LIMIT,
    save_every=SAVE_EVERY,
    system_prompt=SYSTEM_PROMPT,
    progress_every=10,
    resume_from=reviewed_df,
    seen_pmids=reviewed,
    output_path=OUTPUT_PATH,
    log_path=LOG_PATH,
    max_llm_calls=MAX_LLM_CALLS,
    dry_run=DRY_RUN,
)
filtered_df.head()

[2025-11-23T13:00:07] [15272/1000] PMID 25932248 | Acinetobacter baumannii vs Gentamicin | interval 2015/01/01–2019/12/31
[2025-11-23T13:00:08]     decision=yes | rationale=The abstract reports gentamicin-resistant Acinetobacter baumannii isolates and the presence of resistance-related enzyme
[2025-11-23T13:00:09] [15273/1000] PMID 25860039 | Acinetobacter baumannii vs Gentamicin | interval 2015/01/01–2019/12/31
[2025-11-23T13:00:10]     decision=no | rationale=The abstract does not explicitly state resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:00:11] [15275/1000] PMID 25599131 | Acinetobacter baumannii vs Gentamicin | interval 2015/01/01–2019/12/31
[2025-11-23T13:00:12]     decision=yes | rationale=The abstract states that all but one strain of Acinetobacter baumannii were resistant to gentamicin.
[2025-11-23T13:00:13] [15277/1000] PMID 25543268 | Acinetobacter baumannii vs Gentamicin | interval 2015/01/01–2019/12/31
[2025-11-23T13:00:14]     decision=yes | rationale=The abstract states that isolates exhibited low-level resistance to gentamicin.
[2025-11-23T13:00:14] [15278/1000] PMID 24827985 | Acinetobacter baumannii vs Gentamicin | interval 2015/01/01–2019/12/31
[2025-11-23T13:00:15]     decision=yes | rationale=The abstract states that resistance to gentamicin increased during the study period.
[2025-11-23T13:00:15] [15281/1000] PMID 39795127 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:17]     decision=no | rationale=The abstract discusses antimicrobial activity and synergy with gentamicin but does not claim resistance to it.
[2025-11-23T13:00:18] [15283/1000] PMID 39762925 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:19]     decision=no | rationale=The abstract reports low rates of resistance to gentamicin (2.8%) in Acinetobacter baumannii, indicating susceptibility
[2025-11-23T13:00:19] [15284/1000] PMID 39712820 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:20]     decision=no | rationale=The abstract does not explicitly state resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:00:21] [15287/1000] PMID 39634881 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:22]     decision=no | rationale=The abstract does not explicitly state resistance to gentamicin for Acinetobacter baumannii.
[2025-11-23T13:00:22] [15288/1000] PMID 39548455 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:23]     decision=no | rationale=The abstract discusses multidrug resistance but does not explicitly state resistance to gentamicin for A. baumannii.
Processed 10/1000     no:6    yes:4    uncertain:0   |   cumulative 8458     no:6162    yes:2099    uncertain:197
[2025-11-23T13:00:24] [15290/1000] PMID 39493982 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:25]     decision=no | rationale=The abstract discusses resistance in general but does not explicitly state resistance to gentamicin.
[2025-11-23T13:00:25] [15291/1000] PMID 39464903 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:27]     decision=yes | rationale=The abstract states that Acinetobacter baumannii has a resistance rate of 90.5% against gentamicin.
[2025-11-23T13:00:27] [15292/1000] PMID 39452204 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:30]     decision=no | rationale=The abstract states that 31% of isolates showed non-susceptibility to gentamicin but does not explicitly claim resistanc
[2025-11-23T13:00:31] [15293/1000] PMID 39409586 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:32]     decision=no | rationale=The abstract does not claim resistance of Acinetobacter baumannii to Gentamicin.
[2025-11-23T13:00:32] [15294/1000] PMID 39251613 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:34]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:00:34] [15296/1000] PMID 39160825 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:36]     decision=yes | rationale=A. baumannii was resistant to all PLGA NP formulations loaded with gentamicin.
[2025-11-23T13:00:36] [15298/1000] PMID 39007309 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:38]     decision=no | rationale=The abstract mentions gentamicin levels but does not explicitly state resistance for Acinetobacter baumannii.
[2025-11-23T13:00:38] [15299/1000] PMID 39005858 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:40]     decision=yes | rationale=The abstract states that Acinetobacter baumannii strains show considerable resistance to gentamicin.
[2025-11-23T13:00:40] [15301/1000] PMID 38916589 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:41]     decision=yes | rationale=The abstract indicates a significant rise in resistance for Acinetobacter baumannii to gentamicin.
[2025-11-23T13:00:42] [15302/1000] PMID 38910195 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:43]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to gentamicin.
Processed 20/1000     no:12    yes:8    uncertain:0   |   cumulative 8468     no:6168    yes:2103    uncertain:197
[2025-11-23T13:00:44] [15306/1000] PMID 38656082 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:45]     decision=yes | rationale=The abstract reports that gentamicin susceptibility was only 51% among CRAB isolates, indicating significant resistance.
[2025-11-23T13:00:46] [15310/1000] PMID 38399753 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:47]     decision=no | rationale=The abstract states that isolates were susceptible to gentamicin, indicating no resistance.
[2025-11-23T13:00:48] [15311/1000] PMID 38384301 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:49]     decision=no | rationale=The abstract does not explicitly state that Acinetobacter baumannii shows resistance to gentamicin.
[2025-11-23T13:00:50] [15312/1000] PMID 38383429 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:51]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:00:52] [15313/1000] PMID 38227070 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:53]     decision=yes | rationale=The abstract states that the resistance of Acinetobacter baumannii isolates to gentamicin showed a significant increase.
[2025-11-23T13:00:54] [15315/1000] PMID 38063097 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:55]     decision=no | rationale=The abstract does not report any resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:00:55] [15318/1000] PMID 37887252 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:00:56]     decision=yes | rationale=The abstract states that 92.2% of Acinetobacter baumannii isolates were found to be resistant to gentamicin.
[2025-11-23T13:00:57] [15320/1000] PMID 37725828 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:00]     decision=no | rationale=The abstract does not explicitly state resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:01:00] [15322/1000] PMID 37629675 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:02]     decision=yes | rationale=The abstract states that more than 80% of A. baumannii strains were resistant to gentamicin.
[2025-11-23T13:01:03] [15323/1000] PMID 37508294 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:04]     decision=no | rationale=The abstract states that isolates were least resistant to gentamicin (64%) but does not claim significant resistance.
Processed 30/1000     no:18    yes:12    uncertain:0   |   cumulative 8478     no:6174    yes:2107    uncertain:197
[2025-11-23T13:01:05] [15324/1000] PMID 37463121 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:06]     decision=no | rationale=The abstract does not explicitly claim resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:01:06] [15325/1000] PMID 37456417 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:07]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:01:08] [15326/1000] PMID 37428238 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:09]     decision=no | rationale=The abstract discusses multidrug-resistant A. baumannii but does not explicitly state resistance to gentamicin.
[2025-11-23T13:01:10] [15327/1000] PMID 37424668 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:11]     decision=no | rationale=The abstract states increased sensitivity of A. baumannii to gentamicin, not resistance.
[2025-11-23T13:01:12] [15329/1000] PMID 37364734 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:13]     decision=no | rationale=The abstract discusses Acinetobacter seifertii and tigecycline resistance, not Acinetobacter baumannii and gentamicin.
[2025-11-23T13:01:14] [15330/1000] PMID 37286112 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:15]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:01:15] [15331/1000] PMID 37225002 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:16]     decision=yes | rationale=The abstract mentions the presence of the gentamicin resistance gene aadB in the isolate.
[2025-11-23T13:01:17] [15332/1000] PMID 37219451 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:19]     decision=no | rationale=The abstract discusses Enterococcus faecium and its resistance to various antibiotics, not Acinetobacter baumannii or ge
[2025-11-23T13:01:19] [15333/1000] PMID 37176927 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:20]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:01:21] [15336/1000] PMID 37017876 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:22]     decision=no | rationale=The abstract states Acinetobacter baumannii was sensitive to gentamicin, indicating no resistance.
Processed 40/1000     no:27    yes:13    uncertain:0   |   cumulative 8488     no:6183    yes:2108    uncertain:197
[2025-11-23T13:01:23] [15337/1000] PMID 36985130 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:24]     decision=yes | rationale=The abstract states that IC1-IC3 isolates were resistant to gentamicin.
[2025-11-23T13:01:25] [15338/1000] PMID 36825087 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:26]     decision=yes | rationale=The abstract states that all tested A. baumannii isolates were resistant to gentamicin.
[2025-11-23T13:01:26] [15339/1000] PMID 36820613 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:27]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:01:28] [15341/1000] PMID 36648597 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:30]     decision=no | rationale=The abstract states increased sensitivity to gentamicin, not resistance.
[2025-11-23T13:01:30] [15343/1000] PMID 36511707 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:32]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:01:32] [15344/1000] PMID 36432857 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:34]     decision=no | rationale=The abstract discusses the antibacterial activity and synergy but does not explicitly state resistance of Acinetobacter
[2025-11-23T13:01:34] [15346/1000] PMID 36135573 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:35]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to Gentamicin.
[2025-11-23T13:01:36] [15347/1000] PMID 36057417 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:37]     decision=no | rationale=The abstract does not report resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:01:37] [15351/1000] PMID 35922185 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:39]     decision=yes | rationale=The abstract states that the resistance percentage of CSAB isolates to gentamicin is as high as 20%.
[2025-11-23T13:01:40] [15352/1000] PMID 35869778 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:41]     decision=no | rationale=The abstract discusses cefiderocol treatment and does not mention resistance to gentamicin in Acinetobacter baumannii.
[2025-11-23T13:01:41] Checkpoint saved 8498 rows to pmids_results_filtered.parquet
Processed 50/1000     no:34    yes:16    uncertain:0   |   cumulative 8498     no:6190    yes:2111    uncertain:197
[2025-11-23T13:01:42] [15353/1000] PMID 35861511 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:43]     decision=no | rationale=The abstract discusses resistance to polymyxin B, not gentamicin.
[2025-11-23T13:01:44] [15354/1000] PMID 35810245 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:45]     decision=no | rationale=The abstract discusses antibiotic resistance but does not explicitly state resistance to gentamicin in Acinetobacter bau
[2025-11-23T13:01:45] [15356/1000] PMID 35733960 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:46]     decision=no | rationale=The abstract does not report any resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:01:47] [15361/1000] PMID 35395518 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:48]     decision=yes | rationale=The abstract states that Acinetobacter baumannii showed a resistance profile of 25.0% to gentamicin.
[2025-11-23T13:01:48] [15362/1000] PMID 35368079 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:49]     decision=yes | rationale=All CRAB isolates were resistant to gentamicin.
[2025-11-23T13:01:50] [15363/1000] PMID 35355118 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:51]     decision=yes | rationale=The study reports that Acinetobacter baumannii developed resistance to gentamicin after exposure to antidepressants.
[2025-11-23T13:01:51] [15364/1000] PMID 35151875 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:52]     decision=no | rationale=The abstract discusses biofilm formation and treatment synergy but does not explicitly claim resistance to gentamicin.
[2025-11-23T13:01:53] [15365/1000] PMID 35138143 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:54]     decision=no | rationale=The abstract reports susceptibility rates for gentamicin but does not claim significant resistance.
[2025-11-23T13:01:54] [15367/1000] PMID 34969236 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:55]     decision=no | rationale=The abstract states retained sensitivity to gentamicin for Acinetobacter baumannii.
[2025-11-23T13:01:56] [15369/1000] PMID 34952056 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:57]     decision=no | rationale=The abstract discusses reduction of antibiotic-resistant Acinetobacter baumannii but does not claim resistance to gentam
Processed 60/1000     no:41    yes:19    uncertain:0   |   cumulative 8508     no:6197    yes:2114    uncertain:197
[2025-11-23T13:01:58] [15370/1000] PMID 34870473 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:01:59]     decision=no | rationale=The abstract does not mention resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:02:01] [15371/1000] PMID 34835509 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:02]     decision=no | rationale=The abstract does not explicitly state resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:02:02] [15374/1000] PMID 34635960 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:03]     decision=no | rationale=The abstract mentions low resistance to gentamicin but does not claim significant resistance.
[2025-11-23T13:02:04] [15377/1000] PMID 34497596 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:05]     decision=no | rationale=The abstract discusses tigecycline resistance in E. coli, not Acinetobacter baumannii's resistance to gentamicin.
[2025-11-23T13:02:06] [15382/1000] PMID 34250129 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:07]     decision=no | rationale=The abstract does not explicitly state resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:02:07] [15388/1000] PMID 33815505 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:08]     decision=yes | rationale=The abstract states that 43% of Acinetobacter baumannii strains were gentamicin-resistant.
[2025-11-23T13:02:09] [15391/1000] PMID 33533819 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:10]     decision=yes | rationale=The abstract states that 94% of Acinetobacter baumannii isolates were resistant to gentamicin.
[2025-11-23T13:02:10] [15393/1000] PMID 33461493 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:11]     decision=no | rationale=The abstract does not report resistance to gentamicin, only increased susceptibility in a mutant strain.
[2025-11-23T13:02:12] [15394/1000] PMID 33456052 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:13]     decision=no | rationale=The abstract does not claim resistance of Acinetobacter baumannii to gentamicin.
[2025-11-23T13:02:14] [15395/1000] PMID 33452522 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:15]     decision=yes | rationale=Isolates were reported as resistant to gentamicin.
Processed 70/1000     no:48    yes:22    uncertain:0   |   cumulative 8518     no:6204    yes:2117    uncertain:197
[2025-11-23T13:02:15] [15396/1000] PMID 33424412 | Acinetobacter baumannii vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:02:17]     decision=yes | rationale=The abstract states that the maximum degree of resistance was observed against gentamicin (74.55%).

,pmid,decision,rationale,pathogen,antibiotic,title,abstract,start_date,end_date
0,27544979,no,The abstract discusses Achromobacter xylosoxid...,Achromobacter denitrificans,Spectinomycin,Properties of Achromobacter xylosoxidans highl...,We herein discovered a highly resistant clinic...,2015/01/01,2019/12/31
1,15004037,no,The abstract mentions resistance to spectinomy...,Acinetobacter baumannii,Spectinomycin,Molecular epidemiology of sequential outbreaks...,The molecular epidemiology of multidrug-resist...,2000/01/01,2004/12/31
2,19361944,no,The abstract does not explicitly state resista...,Acinetobacter baumannii,Spectinomycin,Genetic basis of resistance to aminoglycosides...,A total of 75 Acinetobacter isolates resistant...,2005/01/01,2009/12/31
3,19028622,no,The abstract does not mention Acinetobacter ba...,Acinetobacter baumannii,Spectinomycin,Nosocomial spread of armA-mediated high-level ...,"1,310 Enterobacteriaceae, 242 Pseudomonas aeru...",2005/01/01,2009/12/31
4,16000417,yes,"The abstract mentions gene aadA1, which confer...",Acinetobacter baumannii,Spectinomycin,Detection and typing of integrons in epidemic ...,Integrons were sought in Acinetobacter isolate...,2005/01/01,2009/12/31

In [5]:

print("Summary (this run):")

reviewed_pmids = set()
if 'reviewed_df' in globals() and reviewed_df is not None and not reviewed_df.empty:
    reviewed_pmids = set(reviewed_df['pmid'].astype(str))

new_df = filtered_df.copy()
if reviewed_pmids:
    new_df = new_df[~new_df['pmid'].astype(str).isin(reviewed_pmids)]

run_total = len(new_df)
run_yes = (new_df['decision'].str.lower() == 'yes').sum()
run_no = (new_df['decision'].str.lower() == 'no').sum()
run_unc = (new_df['decision'].str.lower() == 'uncertain').sum()
run_fraction = run_yes / run_total if run_total else 0
print(f"Processed this run: {run_total} abstracts; yes {run_yes}, no {run_no}, uncertain {run_unc} (yes fraction {run_fraction:.3f}).")

all_total = len(filtered_df)
all_yes = (filtered_df['decision'].str.lower() == 'yes').sum()
all_no = (filtered_df['decision'].str.lower() == 'no').sum()
all_unc = (filtered_df['decision'].str.lower() == 'uncertain').sum()
all_fraction = all_yes / all_total if all_total else 0
print(f"Cumulative: {all_total} abstracts; yes {all_yes}, no {all_no}, uncertain {all_unc} (yes fraction {all_fraction:.3f}).")

if os.path.exists(OUTPUT_PATH):
    tail = open(LOG_PATH, 'r', encoding='utf-8').read().splitlines()
    tail = tail[-10:] if tail else []
    print("Log tail:")
    for line in tail:
        print(line)

Summary (this run):
Processed this run: 778 abstracts; yes 159, no 616, uncertain 3 (yes fraction 0.204).
Cumulative: 9226 abstracts; yes 2254, no 6772, uncertain 200 (yes fraction 0.244).
Log tail:
[2025-11-23T13:24:18] [16558/1000] PMID 33859725 | Clostridioides difficile vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:24:19]     decision=no | rationale=The abstract does not mention resistance of Clostridioides difficile to gentamicin.
[2025-11-23T13:24:19] [16559/1000] PMID 33704685 | Clostridioides difficile vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:24:21]     decision=no | rationale=The abstract does not mention resistance of Clostridioides difficile to gentamicin.
[2025-11-23T13:24:22] [16560/1000] PMID 6998374 | Clostridium botulinum vs Gentamicin | interval 1980/01/01–1984/12/31
[2025-11-23T13:24:23]     decision=yes | rationale=The abstract states that C. botulinum was not susceptible to gentamicin.
[2025-11-23T13:24:23] [16562/1000] PMID 35681327 | Clostridium botulinum vs Gentamicin | interval 2020/01/01–2024/12/31
[2025-11-23T13:24:25]     decision=no | rationale=The abstract does not claim resistance of Clostridium botulinum to gentamicin.
[2025-11-23T13:24:25] Finished: processed 9226 / 1000; positives 2254 (0.244 fraction).
[2025-11-23T13:24:25] Batch summary: yes=2254, no=6772, uncertain=200

In [6]:

print(f"Saved results to {OUTPUT_PATH}")
filtered_df['decision'].value_counts()

Saved results to pmids_results_filtered.parquet

decision
no           6772
yes          2254
uncertain     200
Name: count, dtype: int64

In [7]:

# Build positive-only dataset and save
pmid_df_full = pd.read_parquet("pmids_results.parquet")

# Merge decisions onto exploded PMIDs
positive_flags = filtered_df[filtered_df["decision"].str.lower() == "yes"][["pmid"]].copy()
positive_rows = (
    pmid_df_full.explode("pmids")
    .assign(pmid=lambda d: d["pmids"].astype(str).str.extract(r"(\d+)")[0])
    .dropna(subset=["pmid"])
    .merge(positive_flags, on="pmid", how="inner")
)

# Reassemble to original grain
pmids_positive = (
    positive_rows.groupby(["pathogen", "antibiotic", "start_date", "end_date"], as_index=False)
    .agg(
        pmids=("pmid", list),
        count=("pmid", "size"),
        venue_histogram=("venue_histogram", "first"),
    )
)

positive_path = "pmids_results_positive.parquet"
pmids_positive.to_parquet(positive_path, index=False)
print(f"Saved positive-only dataset to {positive_path} with {len(pmids_positive)} rows")
pmids_positive.head()

Saved positive-only dataset to pmids_results_positive.parquet with 6519 rows

,pathogen,antibiotic,start_date,end_date,pmids,count,venue_histogram
0,Achromobacter denitrificans,Amikacin,1985/01/01,1989/12/31,[3163242],1,"{""Antimicrobial agents and chemotherapy"": 1}"
1,Achromobacter denitrificans,Amikacin,2005/01/01,2009/12/31,[19795625],1,"{""Mikrobiyoloji bulteni"": 1}"
2,Achromobacter denitrificans,Amikacin,2015/01/01,2019/12/31,[26935636],1,"{""Medicine"": 1, ""The Japanese journal of antib..."
3,Achromobacter denitrificans,Amoxicillin,2005/01/01,2009/12/31,"[19795625, 17852927]",2,"{""Mikrobiyoloji bulteni"": 1, ""Scandinavian jou..."
4,Achromobacter denitrificans,Amoxicillin/clavulanic-acid,2005/01/01,2009/12/31,[17852927],1,"{""Scandinavian journal of infectious diseases""..."

In [8]:
pmids_positive[pmids_positive['count']>50]

,pathogen,antibiotic,start_date,end_date,pmids,count,venue_histogram
98,Acinetobacter baumannii,Amikacin,2015/01/01,2019/12/31,"[32313533, 32032023, 31911917, 31706742, 31533...",82,"{""Annals of burns and fire disasters"": 2, ""Jou..."
99,Acinetobacter baumannii,Amikacin,2020/01/01,2024/12/31,"[39958989, 39766586, 39666200, 39418529, 39081...",78,"{""Frontiers in cellular and infection microbio..."
228,Acinetobacter baumannii,Gentamicin,2015/01/01,2019/12/31,"[32032023, 31911917, 31707391, 31667355, 31663...",62,"{""Journal of infection in developing countries..."
229,Acinetobacter baumannii,Gentamicin,2020/01/01,2024/12/31,"[39958989, 39766586, 39666200, 39464903, 39160...",60,"{""Frontiers in cellular and infection microbio..."
2205,Escherichia coli,Amikacin,2010/01/01,2014/12/31,"[25424607, 25379369, 25310915, 25285496, 25246...",67,"{""Journal of Nepal Health Research Council"": 2..."
2206,Escherichia coli,Amikacin,2015/01/01,2019/12/31,"[32045373, 31894059, 31893041, 31855054, 31683...",71,"{""Open access Macedonian journal of medical sc..."
2207,Escherichia coli,Amikacin,2020/01/01,2024/12/31,"[40673002, 39676194, 39619726, 39531253, 39518...",83,"{""JAC-antimicrobial resistance"": 8, ""Public he..."
2803,Klebsiella pneumoniae,Amikacin,2015/01/01,2019/12/31,"[32313533, 32058985, 31921701, 31855054, 31609...",52,"{""Annals of burns and fire disasters"": 1, ""Jou..."
2804,Klebsiella pneumoniae,Amikacin,2020/01/01,2024/12/31,"[39766529, 39734766, 39716087, 39678907, 39547...",90,"{""Archives of Razi Institute"": 5, ""Heliyon"": 3..."
4323,Pseudomonas aeruginosa,Amikacin,2010/01/01,2014/12/31,"[25429232, 25163250, 25141317, 24928215, 24899...",56,"{""Journal of preventive medicine and hygiene"":..."
4324,Pseudomonas aeruginosa,Amikacin,2015/01/01,2019/12/31,"[32313533, 31424553, 31262769, 31187452, 31123...",74,"{""Iranian journal of pharmaceutical research :..."
4325,Pseudomonas aeruginosa,Amikacin,2020/01/01,2024/12/31,"[39906216, 39766586, 39745212, 39659815, 39344...",94,"{""Archives of Razi Institute"": 5, ""Frontiers i..."
4468,Pseudomonas aeruginosa,Ciprofloxacin,2020/01/01,2024/12/31,"[39344345, 39169973, 39160825, 38916589, 38857...",51,"{""Archives of Razi Institute"": 6, ""Microorgani..."