# Filter AMR papers with LLM

Use the `llm.py` helper to ask a model whether a paper's abstract asserts that a pathogen is showing **significant resistance** to a given antibiotic.

In [1]:

# --- LLM filtering configuration ---
import pandas as pd

from llm import create_llm_client
from amr.filtering import (
    DEFAULT_SYSTEM_PROMPT,
    prepare_pmids_to_review,
    run_llm_filter,
)

SYSTEM_PROMPT = """
You are an expert microbiologist reviewing evidence. Given a title and abstract, decide whether the authors explicitly state or conclude that the specified pathogen is showing clinically meaningful resistance to the specified antibiotic.

Rules:
- Answer "yes" only if the abstract clearly reports resistance, reduced susceptibility, treatment failure due to resistance, or emergence of resistant isolates for that pathogen/antibiotic pair.
- Answer "no" if the abstract does not make that claim, is about a different organism/drug, only mentions testing without resistance, or only provides background.
- Answer "uncertain" if the abstract is missing, ambiguous, or only indirectly related.
- Base the decision only on the provided text; do not infer beyond it.

Return compact JSON with keys: decision (yes/no/uncertain) and rationale (one short sentence).
"""

LLM_PROVIDER = "openai"
MODEL_NAME = "gpt-4o-mini"
NCBI_EMAIL = "your_email@example.com"
N_PMIDS_PER_RUN = 1000  # how many unprocessed PMIDs to handle this run
RATE_LIMIT = 0.35  # seconds between PubMed calls
OUTPUT_PATH = "pmids_results_filtered.parquet"
LOG_PATH = "pmid_filter.log"
MAX_LLM_CALLS = None  # set to an integer to cap spend per run
DRY_RUN = False  # set True to skip LLM calls
SAVE_EVERY = 50  # checkpoint frequency

llm_kwargs = {}
if MODEL_NAME:
    llm_kwargs["model"] = MODEL_NAME

llm = create_llm_client(provider=LLM_PROVIDER, **llm_kwargs)
print(f"Using provider={LLM_PROVIDER}, model={MODEL_NAME or 'provider default'}; dry_run={DRY_RUN}; max_llm_calls={MAX_LLM_CALLS}")

Using provider=openai, model=gpt-4o-mini; dry_run=False; max_llm_calls=None

In [2]:
#!pip install openai requests pandas lxml

In [3]:

import os
import pandas as pd
from amr.filtering import prepare_pmids_to_review

# Load previous decisions
if os.path.exists(OUTPUT_PATH):
    reviewed_df = pd.read_parquet(OUTPUT_PATH)
    reviewed = set(reviewed_df['pmid'].astype(str)) if not reviewed_df.empty else set()
    print(f"Resuming with {len(reviewed)} PMIDs already reviewed from {OUTPUT_PATH}")
else:
    reviewed_df = None
    reviewed = set()

pmid_df = pd.read_parquet("pmids_results.parquet")
# Exclude reviewed first, THEN cap to the next chunk
long_df = prepare_pmids_to_review(pmid_df, exclude_pmids=reviewed)

pmid_total = len(long_df)
reviewed_count = len(reviewed)
print(f"Loaded {pmid_total} candidate PMIDs after exclusion; reviewed set size: {reviewed_count}")

if N_PMIDS_PER_RUN:
    long_df = long_df.head(N_PMIDS_PER_RUN)

if len(long_df) == 0:
    print("No PMIDs remain after excluding reviewed. Consider using a fresh OUTPUT_PATH or adding more source data.")

print(f"PMIDs remaining to review this run: {len(long_df)}")
long_df.head()

Resuming with 7237 PMIDs already reviewed from pmids_results_filtered.parquet
Loaded 441907 candidate PMIDs after exclusion; reviewed set size: 7237
PMIDs remaining to review this run: 1000

       pmid             pathogen antibiotic  start_date    end_date
0  23725464    Roseomonas mucosa   Amikacin  2010/01/01  2014/12/31
1  36548814  Rothia dentocariosa   Amikacin  2020/01/01  2024/12/31
2  35622725  Rothia dentocariosa   Amikacin  2020/01/01  2024/12/31
3  18287304  Rothia mucilaginosa   Amikacin  2005/01/01  2009/12/31
4   7329920  Salmonella enterica   Amikacin  1980/01/01  1984/12/31

In [4]:
%%time
filtered_df = run_llm_filter(
    long_df,
    llm,
    email=NCBI_EMAIL,
    rate_limit=RATE_LIMIT,
    save_every=SAVE_EVERY,
    system_prompt=SYSTEM_PROMPT,
    progress_every=10,
    resume_from=reviewed_df,
    seen_pmids=reviewed,
    output_path=OUTPUT_PATH,
    log_path=LOG_PATH,
    max_llm_calls=MAX_LLM_CALLS,
    dry_run=DRY_RUN,
)
filtered_df.head()

[1/1000] PMID 23725464 | Roseomonas mucosa vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract states the organism is generally susceptible to aminoglycosides, including amikacin.
[2/1000] PMID 36548814 | Rothia dentocariosa vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract does not mention resistance of Rothia dentocariosa to amikacin.
[3/1000] PMID 35622725 | Rothia dentocariosa vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract only mentions that amikacin effectively inhibits the growth of Rothia nasimurium without stating any resist
[4/1000] PMID 18287304 | Rothia mucilaginosa vs Amikacin | interval 2005/01/01–2009/12/31
    decision=yes | rationale=The isolate was multidrug-resistant and the patient had initial trials with amikacin.
[5/1000] PMID 7329920 | Salmonella enterica vs Amikacin | interval 1980/01/01–1984/12/31
    decision=no | rationale=The abstract does not report resistance of Salmonella enterica to amikacin.
[6/1000] PMID 2682793 | Salmonella enterica vs Amikacin | interval 1985/01/01–1989/12/31
    decision=no | rationale=The abstract states that 100% of Salmonella strains were sensitive to amikacin.
[7/1000] PMID 2516600 | Salmonella enterica vs Amikacin | interval 1985/01/01–1989/12/31
    decision=no | rationale=The abstract states that Salmonella paratyphi B is usually sensitive to amikacin.
[8/1000] PMID 7957789 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract states that all strains were uniformly susceptible to amikacin.
[9/1000] PMID 7802340 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract discusses resistance in Salmonella typhi but does not mention resistance to amikacin.
[10/1000] PMID 8373850 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract states that Salmonella isolates were sensitive to amikacin, indicating no resistance.
Processed 7247/1000    no:9    yes:1    uncertain:0
[11/1000] PMID 8222893 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract does not mention resistance to amikacin or any other antibiotic.
[12/1000] PMID 8426772 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=yes | rationale=The abstract states that 92.8% of strains were resistant to amikacin.
[13/1000] PMID 8354556 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract states Salmonella typhi is sensitive to amikacin.
[14/1000] PMID 1398852 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract states that Salmonella typhi is sensitive to amikacin.
[15/1000] PMID 1800080 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract states Salmonella typhimurium is mostly sensitive to amikacin, indicating no resistance.
[16/1000] PMID 1913133 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract states that no strains resistant to amikacin were detected.
[17/1000] PMID 2089238 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract indicates sensitivity to amikacin, not resistance.
[18/1000] PMID 2182815 | Salmonella enterica vs Amikacin | interval 1990/01/01–1994/12/31
    decision=no | rationale=The abstract mentions multiple drug resistance but does not specify resistance to amikacin.
[19/1000] PMID 9835490 | Salmonella enterica vs Amikacin | interval 1995/01/01–1999/12/31
    decision=yes | rationale=The abstract states that 20% of the isolates were resistant to amikacin.
[20/1000] PMID 9459410 | Salmonella enterica vs Amikacin | interval 1995/01/01–1999/12/31
    decision=no | rationale=The abstract discusses quinolone resistance, not amikacin resistance.
Processed 7257/1000    no:17    yes:3    uncertain:0
[21/1000] PMID 9868065 | Salmonella enterica vs Amikacin | interval 1995/01/01–1999/12/31
    decision=no | rationale=The abstract states that 100% of the strains were sensitive to amikacin.
[22/1000] PMID 8940427 | Salmonella enterica vs Amikacin | interval 1995/01/01–1999/12/31
    decision=yes | rationale=The abstract states that Salmonella typhimurium is resistant to amikacin.
[23/1000] PMID 9387569 | Salmonella enterica vs Amikacin | interval 1995/01/01–1999/12/31
    decision=no | rationale=The abstract does not mention resistance of Salmonella enterica to amikacin.
[24/1000] PMID 9251374 | Salmonella enterica vs Amikacin | interval 1995/01/01–1999/12/31
    decision=yes | rationale=The abstract states that 50% of Salmonella typhi showed resistance to amikacin.
[25/1000] PMID 17217005 | Salmonella enterica vs Amikacin | interval 1995/01/01–1999/12/31
    decision=no | rationale=The abstract states that S. typhi is sensitive to amikacin.
[26/1000] PMID 8635831 | Salmonella enterica vs Amikacin | interval 1995/01/01–1999/12/31
    decision=no | rationale=The abstract does not mention resistance of Salmonella enterica to amikacin.
[27/1000] PMID 7653025 | Salmonella enterica vs Amikacin | interval 1995/01/01–1999/12/31
    decision=no | rationale=The abstract does not report resistance of Salmonella enterica to amikacin.
[28/1000] PMID 15471142 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=no | rationale=The abstract states the isolate is sensitive to amikacin, indicating no resistance.
[29/1000] PMID 15140394 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=no | rationale=All Salmonella isolates tested were susceptible to amikacin.
[30/1000] PMID 15035356 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=no | rationale=The abstract states that all isolates were sensitive to amikacin.
Processed 7267/1000    no:25    yes:5    uncertain:0
[31/1000] PMID 15022937 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=yes | rationale=The abstract states that the isolates were found to be resistant to amikacin.
[32/1000] PMID 14596347 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=no | rationale=The abstract states 100% susceptibility to amikacin, indicating no resistance.
[33/1000] PMID 12543680 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=yes | rationale=The abstract reports high levels of resistance to amikacin in Salmonella enterica.
[34/1000] PMID 12523640 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=no | rationale=The abstract does not report resistance of Salmonella enterica to amikacin.
[35/1000] PMID 12089972 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=no | rationale=The abstract does not mention resistance to Amikacin specifically.
[36/1000] PMID 11980609 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=no | rationale=The abstract states that the isolate is sensitive to amikacin, indicating no resistance.
[37/1000] PMID 11798253 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=no | rationale=The abstract states all isolates were susceptible to amikacin.
[38/1000] PMID 11516040 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=yes | rationale=The isolate was reported as resistant to amikacin.
[39/1000] PMID 10991889 | Salmonella enterica vs Amikacin | interval 2000/01/01–2004/12/31
    decision=yes | rationale=The abstract states that Salmonella enterica shows resistance to amikacin.
[40/1000] PMID 19902796 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract does not report resistance of Salmonella enterica to amikacin specifically.
Processed 7277/1000    no:31    yes:9    uncertain:0
[41/1000] PMID 19831314 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract does not report any resistance to amikacin for Salmonella enterica.
[42/1000] PMID 19554971 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract reports sensitivity to amikacin, not resistance.
[43/1000] PMID 19418032 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=yes | rationale=The strain was reported as resistant to amikacin.
[44/1000] PMID 19255695 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract states that all isolates were susceptible to amikacin.
[45/1000] PMID 18977678 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract states that no resistance was detected to amikacin in Salmonella Typhimurium.
[46/1000] PMID 18383953 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract reports high sensitivity to amikacin (98%) without mentioning resistance.
[47/1000] PMID 17931817 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract does not report resistance or reduced susceptibility of Salmonella enterica to amikacin.
[48/1000] PMID 17921438 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract states that all isolates were sensitive to amikacin.
[49/1000] PMID 17607044 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract states that no resistance to amikacin was detected.
[50/1000] PMID 27407999 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract reports sensitivity to amikacin without indicating resistance.
Checkpoint saved 7287 rows to pmids_results_filtered.parquet
Processed 7287/1000    no:40    yes:10    uncertain:0
[51/1000] PMID 16642766 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=yes | rationale=The abstract states that all strains showed resistance to amikacin.
[52/1000] PMID 16329607 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract states Salmonella typhimurium is susceptible to amikacin.
[53/1000] PMID 15928436 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract does not report resistance of Salmonella enterica to amikacin.
[54/1000] PMID 15750057 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=yes | rationale=The abstract states that Salmonella enterica is resistant to amikacin.
[55/1000] PMID 15699587 | Salmonella enterica vs Amikacin | interval 2005/01/01–2009/12/31
    decision=no | rationale=The abstract states that Salmonella isolates were 100% susceptible to amikacin.
[56/1000] PMID 25528352 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract reports low resistance to amikacin (3.7%) without indicating clinical significance.
[57/1000] PMID 25218754 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=yes | rationale=The abstract states that 20.0% of Salmonella enterica isolates were resistant to amikacin.
[58/1000] PMID 24788434 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract states that 95% of the isolates were sensitive to amikacin, indicating no significant resistance.
[59/1000] PMID 24724034 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=yes | rationale=The abstract states that all 20 S. enterica isolates showed 100% resistance to amikacin.
[60/1000] PMID 23320422 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=yes | rationale=The abstract explicitly states that one strain of Salmonella enterica is resistant to amikacin.
Processed 7297/1000    no:45    yes:15    uncertain:0
[61/1000] PMID 22961898 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract does not explicitly state resistance of Salmonella enterica to amikacin.
[62/1000] PMID 22488050 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=yes | rationale=The abstract states that all Salmonella isolates were resistant to amikacin.
[63/1000] PMID 22259250 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract reports a lower percentage of resistance for amikacin (9.9%) in Salmonella enterica, indicating no signific
[64/1000] PMID 22014730 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract states S. typhi is 100% susceptible to amikacin, indicating no resistance.
[65/1000] PMID 21929877 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=yes | rationale=The abstract states that the isolates were resistant to amikacin.
[66/1000] PMID 21919733 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract reports low percentages of resistance to amikacin but does not claim clinically meaningful resistance.
[67/1000] PMID 21083518 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract states that 4.5% of S. indiana isolates were susceptible to amikacin, indicating no significant resistance.
[68/1000] PMID 20939741 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract does not explicitly state resistance of Salmonella enterica to amikacin.
[69/1000] PMID 20639314 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=yes | rationale=The abstract states that strain Se20 was resistant to amikacin.
[70/1000] PMID 20409348 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=yes | rationale=The abstract states that isolates exhibited high resistance against amikacin (44%).
Processed 7307/1000    no:51    yes:19    uncertain:0
[71/1000] PMID 20402413 | Salmonella enterica vs Amikacin | interval 2010/01/01–2014/12/31
    decision=no | rationale=The abstract states that no resistance was observed to amikacin in Salmonella enteritidis isolates.
[72/1000] PMID 31884559 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract states that all Salmonella isolates were 100% susceptible to amikacin.
[73/1000] PMID 30912318 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=yes | rationale=The abstract states that the flight strain displayed enhanced amikacin resistance.
[74/1000] PMID 30504956 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract states only one isolate showed sensitivity to amikacin, indicating no resistance claim.
[75/1000] PMID 30445474 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=yes | rationale=The abstract states that Salmonella enterica serovar Indiana isolates expressed high-level resistance to amikacin.
[76/1000] PMID 30351266 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract states that Salmonella enterica remains susceptible to amikacin.
[77/1000] PMID 29875924 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract reports sensitivity to amikacin without indicating resistance.
[78/1000] PMID 29164140 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract states that SH UFPR1 was susceptible to amikacin.
[79/1000] PMID 28957726 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=yes | rationale=The abstract reports concurrent resistance of Salmonella enterica to amikacin.
[80/1000] PMID 28784420 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=yes | rationale=The abstract states that Salmonella enterica isolates showed resistance against Amikacin.
Processed 7317/1000    no:57    yes:23    uncertain:0
[81/1000] PMID 28769915 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract does not report resistance of Salmonella enterica to amikacin.
[82/1000] PMID 28375673 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=yes | rationale=The abstract states that 20.0% of Salmonella isolates showed resistance to amikacin.
[83/1000] PMID 27660816 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract states that most isolates were susceptible to amikacin.
[84/1000] PMID 27051204 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract mentions 30% sensitivity to amikacin but does not report resistance.
[85/1000] PMID 25692653 | Salmonella enterica vs Amikacin | interval 2015/01/01–2019/12/31
    decision=yes | rationale=Salmonella Enteritidis isolates were reported as resistant to amikacin.
[86/1000] PMID 40303054 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=yes | rationale=The abstract states that Salmonella isolates were highly resistant to amikacin (100%).
[87/1000] PMID 38965941 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=yes | rationale=The abstract states that Salmonella typhi was resistant to amikacin.
[88/1000] PMID 38938436 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=yes | rationale=The abstract states resistance to Amikacin in human isolates and chicken products.
[89/1000] PMID 38686255 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract reports high sensitivity of amikacin without mentioning resistance.
[90/1000] PMID 38430331 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract does not claim resistance of Salmonella enterica to amikacin.
Processed 7327/1000    no:62    yes:28    uncertain:0
[91/1000] PMID 38122981 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract states the isolate is susceptible to amikacin.
[92/1000] PMID 38097737 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract states Salmonella enterica is more susceptible to Amikacin, indicating no significant resistance.
[93/1000] PMID 37228010 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract states that Salmonella spp. isolates were highly susceptible to amikacin, indicating no resistance.
[94/1000] PMID 37082540 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract states that no isolates were resistant to amikacin.
[95/1000] PMID 36854357 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract states that S. Indiana QT6365 exhibited resistance to all tested antimicrobials except for amikacin, indica
[96/1000] PMID 36141052 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract reports high susceptibility to amikacin with no mention of resistance.
[97/1000] PMID 35812262 | Salmonella enterica vs Amikacin | interval 2020/01/01–2024/12/31
    decision=no | rationale=The abstract indicates over 80% susceptibility to Amikacin, not resistance.

,pmid,decision,rationale,pathogen,antibiotic,title,abstract,start_date,end_date
0,27544979,no,The abstract discusses Achromobacter xylosoxid...,Achromobacter denitrificans,Spectinomycin,Properties of Achromobacter xylosoxidans highl...,We herein discovered a highly resistant clinic...,2015/01/01,2019/12/31
1,15004037,no,The abstract mentions resistance to spectinomy...,Acinetobacter baumannii,Spectinomycin,Molecular epidemiology of sequential outbreaks...,The molecular epidemiology of multidrug-resist...,2000/01/01,2004/12/31
2,19361944,no,The abstract does not explicitly state resista...,Acinetobacter baumannii,Spectinomycin,Genetic basis of resistance to aminoglycosides...,A total of 75 Acinetobacter isolates resistant...,2005/01/01,2009/12/31
3,19028622,no,The abstract does not mention Acinetobacter ba...,Acinetobacter baumannii,Spectinomycin,Nosocomial spread of armA-mediated high-level ...,"1,310 Enterobacteriaceae, 242 Pseudomonas aeru...",2005/01/01,2009/12/31
4,16000417,yes,"The abstract mentions gene aadA1, which confer...",Acinetobacter baumannii,Spectinomycin,Detection and typing of integrons in epidemic ...,Integrons were sought in Acinetobacter isolate...,2005/01/01,2009/12/31

In [5]:

print("Summary (this run):")

reviewed_pmids = set()
if 'reviewed_df' in globals() and reviewed_df is not None and not reviewed_df.empty:
    reviewed_pmids = set(reviewed_df['pmid'].astype(str))

new_df = filtered_df.copy()
if reviewed_pmids:
    new_df = new_df[~new_df['pmid'].astype(str).isin(reviewed_pmids)]

run_total = len(new_df)
run_yes = (new_df['decision'].str.lower() == 'yes').sum()
run_no = (new_df['decision'].str.lower() == 'no').sum()
run_unc = (new_df['decision'].str.lower() == 'uncertain').sum()
run_fraction = run_yes / run_total if run_total else 0
print(f"Processed this run: {run_total} abstracts; yes {run_yes}, no {run_no}, uncertain {run_unc} (yes fraction {run_fraction:.3f}).")

all_total = len(filtered_df)
all_yes = (filtered_df['decision'].str.lower() == 'yes').sum()
all_no = (filtered_df['decision'].str.lower() == 'no').sum()
all_unc = (filtered_df['decision'].str.lower() == 'uncertain').sum()
all_fraction = all_yes / all_total if all_total else 0
print(f"Cumulative: {all_total} abstracts; yes {all_yes}, no {all_no}, uncertain {all_unc} (yes fraction {all_fraction:.3f}).")

if os.path.exists(OUTPUT_PATH):
    tail = open(LOG_PATH, 'r', encoding='utf-8').read().splitlines()
    tail = tail[-10:] if tail else []
    print("
Log tail:")
    for line in tail:
        print(line)

Summary (this run):
Processed 8060 abstracts; positives 2008 (0.249).
Cumulative: 8060 abstracts; positives 2008 (0.249).
Log tail:
[973/1000] PMID 26182813 | Haemophilus influenzae vs Arbekacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract does not mention resistance of Haemophilus influenzae to arbekacin.
[974/1000] PMID 25980052 | Haemophilus influenzae vs Arbekacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract does not mention resistance of Haemophilus influenzae to arbekacin.
[975/1000] PMID 25980051 | Haemophilus influenzae vs Arbekacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract does not report any resistance of Haemophilus influenzae to arbekacin.
[976/1000] PMID 25980050 | Haemophilus influenzae vs Arbekacin | interval 2015/01/01–2019/12/31
    decision=no | rationale=The abstract does not mention resistance of Haemophilus influenzae to arbekacin.
Finished: processed 8060 / 1000; positives 2008 (0.249 fraction).
Batch summary: yes=2008, no=5876, uncertain=176

In [6]:

print(f"Saved results to {OUTPUT_PATH}")
filtered_df['decision'].value_counts()

Saved results to pmids_results_filtered.parquet

decision
no           5876
yes          2008
uncertain     176
Name: count, dtype: int64

In [7]:

# Build positive-only dataset and save
pmid_df_full = pd.read_parquet("pmids_results.parquet")

# Merge decisions onto exploded PMIDs
positive_flags = filtered_df[filtered_df["decision"].str.lower() == "yes"][["pmid"]].copy()
positive_rows = (
    pmid_df_full.explode("pmids")
    .assign(pmid=lambda d: d["pmids"].astype(str).str.extract(r"(\d+)")[0])
    .dropna(subset=["pmid"])
    .merge(positive_flags, on="pmid", how="inner")
)

# Reassemble to original grain
pmids_positive = (
    positive_rows.groupby(["pathogen", "antibiotic", "start_date", "end_date"], as_index=False)
    .agg(
        pmids=("pmid", list),
        count=("pmid", "size"),
        venue_histogram=("venue_histogram", "first"),
    )
)

positive_path = "pmids_results_positive.parquet"
pmids_positive.to_parquet(positive_path, index=False)
print(f"Saved positive-only dataset to {positive_path} with {len(pmids_positive)} rows")
pmids_positive.head()

Saved positive-only dataset to pmids_results_positive.parquet with 5568 rows

,pathogen,antibiotic,start_date,end_date,pmids,count,venue_histogram
0,Achromobacter denitrificans,Amikacin,1985/01/01,1989/12/31,[3163242],1,"{""Antimicrobial agents and chemotherapy"": 1}"
1,Achromobacter denitrificans,Amikacin,2005/01/01,2009/12/31,[19795625],1,"{""Mikrobiyoloji bulteni"": 1}"
2,Achromobacter denitrificans,Amikacin,2015/01/01,2019/12/31,[26935636],1,"{""Medicine"": 1, ""The Japanese journal of antib..."
3,Achromobacter denitrificans,Amoxicillin,2005/01/01,2009/12/31,[19795625],1,"{""Mikrobiyoloji bulteni"": 1, ""Scandinavian jou..."
4,Achromobacter denitrificans,Ampicillin,1985/01/01,1989/12/31,[3163242],1,"{""The Japanese journal of antibiotics"": 1, ""An..."

In [8]:
pmids_positive[pmids_positive['count']>50]

,pathogen,antibiotic,start_date,end_date,pmids,count,venue_histogram
58,Acinetobacter baumannii,Amikacin,2015/01/01,2019/12/31,"[32313533, 32032023, 31911917, 31706742, 31533...",82,"{""Annals of burns and fire disasters"": 2, ""Jou..."
59,Acinetobacter baumannii,Amikacin,2020/01/01,2024/12/31,"[39958989, 39766586, 39666200, 39418529, 39081...",78,"{""Frontiers in cellular and infection microbio..."
1575,Escherichia coli,Amikacin,2010/01/01,2014/12/31,"[25424607, 25379369, 25310915, 25285496, 25246...",67,"{""Journal of Nepal Health Research Council"": 2..."
1576,Escherichia coli,Amikacin,2015/01/01,2019/12/31,"[32045373, 31894059, 31893041, 31855054, 31683...",71,"{""Open access Macedonian journal of medical sc..."
1577,Escherichia coli,Amikacin,2020/01/01,2024/12/31,"[40673002, 39676194, 39619726, 39531253, 39518...",83,"{""JAC-antimicrobial resistance"": 8, ""Public he..."
2133,Klebsiella pneumoniae,Amikacin,2015/01/01,2019/12/31,"[32313533, 32058985, 31921701, 31855054, 31609...",52,"{""Annals of burns and fire disasters"": 1, ""Jou..."
2134,Klebsiella pneumoniae,Amikacin,2020/01/01,2024/12/31,"[39766529, 39734766, 39716087, 39678907, 39547...",90,"{""Archives of Razi Institute"": 5, ""Heliyon"": 3..."
3523,Pseudomonas aeruginosa,Amikacin,2010/01/01,2014/12/31,"[25429232, 25163250, 25141317, 24928215, 24899...",56,"{""Journal of preventive medicine and hygiene"":..."
3524,Pseudomonas aeruginosa,Amikacin,2015/01/01,2019/12/31,"[32313533, 31424553, 31262769, 31187452, 31123...",74,"{""Iranian journal of pharmaceutical research :..."
3525,Pseudomonas aeruginosa,Amikacin,2020/01/01,2024/12/31,"[39906216, 39766586, 39745212, 39659815, 39344...",94,"{""Archives of Razi Institute"": 5, ""Frontiers i..."