# Yearly AMR Pair Counts from PubMed Dates

This notebook addresses the main limitation of the interval-based AMR workflow: the current positive dataset is stored in 5-year bins, while the scientific-interest analysis would be cleaner on true publication years.

The workflow here is:

1. load the current `pmids_results_positive.parquet`
2. explode interval-level PMID lists into one row per `(pathogen, antibiotic, pmid)` association
3. query PubMed `esummary` to recover publication dates for each PMID
4. cache those PMID-level metadata locally so the process can be resumed
5. save both:
   - a pair-PMID association table with publication dates
   - a yearly AMR count table aggregated by `(pathogen, antibiotic, year)`

In [4]:
from pathlib import Path
import os

import pandas as pd

from amr.pubmed.yearly import (
    explode_positive_pair_pmids,
    load_pubmed_metadata_cache,
    refresh_pubmed_metadata_cache,
    attach_pubmed_metadata,
    aggregate_pair_counts_by_year,
    summarize_metadata_coverage,
)

DATA_DIR = Path(".")
POSITIVE_PATH = DATA_DIR / "pmids_results_positive.parquet"
CACHE_PATH = DATA_DIR / "pubmed_pmid_metadata.parquet"
PAIR_PMID_PATH = DATA_DIR / "pmids_results_positive_pair_pmid.parquet"
YEARLY_PATH = DATA_DIR / "pmids_results_positive_yearly.parquet"

PUBMED_EMAIL = os.environ.get("PUBMED_EMAIL", "xfcosta@gmail.com")
BATCH_SIZE = 200
CHECKPOINT_EVERY_BATCHES = 10

POSITIVE_PATH

PosixPath('pmids_results_positive.parquet')

## Load the current positive dataset

The existing positive parquet stores one row per `(pathogen, antibiotic, 5-year interval)` and keeps the matching PMIDs as a list. We first expand that into a true pair-PMID table.

In [5]:
positive_df = pd.read_parquet(POSITIVE_PATH)
pair_pmid_df = explode_positive_pair_pmids(positive_df)

print(f"interval rows: {len(positive_df):,}")
print(f"pair-PMID rows: {len(pair_pmid_df):,}")
print(f"unique PMIDs: {pair_pmid_df['pmid'].nunique():,}")

pair_pmid_df.head()

interval rows: 24,049
pair-PMID rows: 154,906
unique PMIDs: 63,316

                pathogen     antibiotic  start_date    end_date      pmid
0  Abiotrophia defectiva       Cefepime  2015/01/01  2019/12/31  27216060
1  Abiotrophia defectiva     Cefotaxime  2015/01/01  2019/12/31  27216060
2  Abiotrophia defectiva    Ceftriaxone  2010/01/01  2014/12/31  24034902
3  Abiotrophia defectiva  Ciprofloxacin  2010/01/01  2014/12/31  24034902
4  Abiotrophia defectiva    Clindamycin  2000/01/01  2004/12/31  10681362

## Fetch and cache PubMed dates

The helper below looks for an existing PMID metadata cache first. Only PMIDs that are still missing will be queried from PubMed.

Set a real email before running the fetch step, for example:

```bash
export PUBMED_EMAIL="your.name@example.com"
```

NCBI expects a real contact email for automated E-utilities requests.

In [6]:
cache_df = load_pubmed_metadata_cache(CACHE_PATH)
requested_pmids = pair_pmid_df["pmid"].astype(str).unique()
missing_pmids = sorted(set(requested_pmids) - set(cache_df["pmid"].astype(str)))

print(f"cached PMIDs: {cache_df['pmid'].nunique():,}")
print(f"missing PMIDs: {len(missing_pmids):,}")

if missing_pmids and PUBMED_EMAIL == "your_email@example.com":
    raise ValueError(
        "Set PUBMED_EMAIL to a real email address before fetching missing PubMed metadata."
    )

if missing_pmids:
    cache_df = refresh_pubmed_metadata_cache(
        requested_pmids,
        cache_path=CACHE_PATH,
        email=PUBMED_EMAIL,
        batch_size=BATCH_SIZE,
        checkpoint_every_batches=CHECKPOINT_EVERY_BATCHES,
    )

cache_df.head()

cached PMIDs: 0
missing PMIDs: 63,316
Fetching PubMed metadata for 63316 missing PMIDs (0 already cached).
Fetched batch 1/317 (200 PMIDs).
Fetched batch 2/317 (200 PMIDs).
Fetched batch 3/317 (200 PMIDs).
Fetched batch 4/317 (200 PMIDs).
Fetched batch 5/317 (200 PMIDs).
Fetched batch 6/317 (200 PMIDs).
Fetched batch 7/317 (200 PMIDs).
Fetched batch 8/317 (200 PMIDs).
Fetched batch 9/317 (200 PMIDs).
Fetched batch 10/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.

/mnt/data/sync/Projects/Pathogen Atlas/Antimicrobial Resistance/amr/pubmed/yearly.py:136: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  checkpoint_df = pd.concat([cache_df, pd.DataFrame(new_rows)], ignore_index=True)

Fetched batch 11/317 (200 PMIDs).
Fetched batch 12/317 (200 PMIDs).
Fetched batch 13/317 (200 PMIDs).
Fetched batch 14/317 (200 PMIDs).
Fetched batch 15/317 (200 PMIDs).
Fetched batch 16/317 (200 PMIDs).
Fetched batch 17/317 (200 PMIDs).
Fetched batch 18/317 (200 PMIDs).
Fetched batch 19/317 (200 PMIDs).
Fetched batch 20/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 21/317 (200 PMIDs).
Fetched batch 22/317 (200 PMIDs).
Fetched batch 23/317 (200 PMIDs).
Fetched batch 24/317 (200 PMIDs).
Fetched batch 25/317 (200 PMIDs).
Fetched batch 26/317 (200 PMIDs).
Fetched batch 27/317 (200 PMIDs).
Fetched batch 28/317 (200 PMIDs).
Fetched batch 29/317 (200 PMIDs).
Fetched batch 30/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 31/317 (200 PMIDs).
Fetched batch 32/317 (200 PMIDs).
Fetched batch 33/317 (200 PMIDs).
Fetched batch 34/317 (200 PMIDs).
Fetched batch 35/317 (200 PMIDs).
Fetched batch 36/317 (200 PMIDs).
Fetched batch 37/317 (200 PMIDs).
Fetched batch 38/317 (200 PMIDs).
Fetched batch 39/317 (200 PMIDs).
Fetched batch 40/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 41/317 (200 PMIDs).
Fetched batch 42/317 (200 PMIDs).
Fetched batch 43/317 (200 PMIDs).
Fetched batch 44/317 (200 PMIDs).
Fetched batch 45/317 (200 PMIDs).
Fetched batch 46/317 (200 PMIDs).
Fetched batch 47/317 (200 PMIDs).
Fetched batch 48/317 (200 PMIDs).
Fetched batch 49/317 (200 PMIDs).
Fetched batch 50/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 51/317 (200 PMIDs).
Fetched batch 52/317 (200 PMIDs).
Fetched batch 53/317 (200 PMIDs).
Fetched batch 54/317 (200 PMIDs).
Fetched batch 55/317 (200 PMIDs).
Fetched batch 56/317 (200 PMIDs).
Fetched batch 57/317 (200 PMIDs).
Fetched batch 58/317 (200 PMIDs).
Fetched batch 59/317 (200 PMIDs).
Fetched batch 60/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 61/317 (200 PMIDs).
Fetched batch 62/317 (200 PMIDs).
Fetched batch 63/317 (200 PMIDs).
Fetched batch 64/317 (200 PMIDs).
Fetched batch 65/317 (200 PMIDs).
Fetched batch 66/317 (200 PMIDs).
Fetched batch 67/317 (200 PMIDs).
Fetched batch 68/317 (200 PMIDs).
Fetched batch 69/317 (200 PMIDs).
Fetched batch 70/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 71/317 (200 PMIDs).
Fetched batch 72/317 (200 PMIDs).
Fetched batch 73/317 (200 PMIDs).
Fetched batch 74/317 (200 PMIDs).
Fetched batch 75/317 (200 PMIDs).
Fetched batch 76/317 (200 PMIDs).
Fetched batch 77/317 (200 PMIDs).
Fetched batch 78/317 (200 PMIDs).
Fetched batch 79/317 (200 PMIDs).
Fetched batch 80/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 81/317 (200 PMIDs).
Fetched batch 82/317 (200 PMIDs).
Fetched batch 83/317 (200 PMIDs).
Fetched batch 84/317 (200 PMIDs).
Fetched batch 85/317 (200 PMIDs).
Fetched batch 86/317 (200 PMIDs).
Fetched batch 87/317 (200 PMIDs).
Fetched batch 88/317 (200 PMIDs).
Fetched batch 89/317 (200 PMIDs).
Fetched batch 90/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 91/317 (200 PMIDs).
Fetched batch 92/317 (200 PMIDs).
Fetched batch 93/317 (200 PMIDs).
Fetched batch 94/317 (200 PMIDs).
Fetched batch 95/317 (200 PMIDs).
Fetched batch 96/317 (200 PMIDs).
Fetched batch 97/317 (200 PMIDs).
Fetched batch 98/317 (200 PMIDs).
Fetched batch 99/317 (200 PMIDs).
Fetched batch 100/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 101/317 (200 PMIDs).
Fetched batch 102/317 (200 PMIDs).
Fetched batch 103/317 (200 PMIDs).
Fetched batch 104/317 (200 PMIDs).
Fetched batch 105/317 (200 PMIDs).
Fetched batch 106/317 (200 PMIDs).
Fetched batch 107/317 (200 PMIDs).
Fetched batch 108/317 (200 PMIDs).
Fetched batch 109/317 (200 PMIDs).
Fetched batch 110/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 111/317 (200 PMIDs).
Fetched batch 112/317 (200 PMIDs).
Fetched batch 113/317 (200 PMIDs).
Fetched batch 114/317 (200 PMIDs).
Fetched batch 115/317 (200 PMIDs).
Fetched batch 116/317 (200 PMIDs).
Fetched batch 117/317 (200 PMIDs).
Fetched batch 118/317 (200 PMIDs).
Fetched batch 119/317 (200 PMIDs).
Fetched batch 120/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 121/317 (200 PMIDs).
Fetched batch 122/317 (200 PMIDs).
Fetched batch 123/317 (200 PMIDs).
Fetched batch 124/317 (200 PMIDs).
Fetched batch 125/317 (200 PMIDs).
Fetched batch 126/317 (200 PMIDs).
Fetched batch 127/317 (200 PMIDs).
Fetched batch 128/317 (200 PMIDs).
Fetched batch 129/317 (200 PMIDs).
Fetched batch 130/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 131/317 (200 PMIDs).
Fetched batch 132/317 (200 PMIDs).
Fetched batch 133/317 (200 PMIDs).
Fetched batch 134/317 (200 PMIDs).
Fetched batch 135/317 (200 PMIDs).
Fetched batch 136/317 (200 PMIDs).
Fetched batch 137/317 (200 PMIDs).
Fetched batch 138/317 (200 PMIDs).
Fetched batch 139/317 (200 PMIDs).
Fetched batch 140/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 141/317 (200 PMIDs).
Fetched batch 142/317 (200 PMIDs).
Fetched batch 143/317 (200 PMIDs).
Fetched batch 144/317 (200 PMIDs).
Fetched batch 145/317 (200 PMIDs).
Fetched batch 146/317 (200 PMIDs).
Fetched batch 147/317 (200 PMIDs).
Fetched batch 148/317 (200 PMIDs).
Fetched batch 149/317 (200 PMIDs).
Fetched batch 150/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 151/317 (200 PMIDs).
Fetched batch 152/317 (200 PMIDs).
Fetched batch 153/317 (200 PMIDs).
Fetched batch 154/317 (200 PMIDs).
Fetched batch 155/317 (200 PMIDs).
Fetched batch 156/317 (200 PMIDs).
Fetched batch 157/317 (200 PMIDs).
Fetched batch 158/317 (200 PMIDs).
Fetched batch 159/317 (200 PMIDs).
Fetched batch 160/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 161/317 (200 PMIDs).
Fetched batch 162/317 (200 PMIDs).
Fetched batch 163/317 (200 PMIDs).
Fetched batch 164/317 (200 PMIDs).
Fetched batch 165/317 (200 PMIDs).
Fetched batch 166/317 (200 PMIDs).
Fetched batch 167/317 (200 PMIDs).
Fetched batch 168/317 (200 PMIDs).
Fetched batch 169/317 (200 PMIDs).
Fetched batch 170/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 171/317 (200 PMIDs).
Fetched batch 172/317 (200 PMIDs).
Fetched batch 173/317 (200 PMIDs).
Fetched batch 174/317 (200 PMIDs).
Fetched batch 175/317 (200 PMIDs).
Fetched batch 176/317 (200 PMIDs).
Fetched batch 177/317 (200 PMIDs).
Fetched batch 178/317 (200 PMIDs).
Fetched batch 179/317 (200 PMIDs).
Fetched batch 180/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 181/317 (200 PMIDs).
Fetched batch 182/317 (200 PMIDs).
Fetched batch 183/317 (200 PMIDs).
Fetched batch 184/317 (200 PMIDs).
Fetched batch 185/317 (200 PMIDs).
Fetched batch 186/317 (200 PMIDs).
Fetched batch 187/317 (200 PMIDs).
Fetched batch 188/317 (200 PMIDs).
Fetched batch 189/317 (200 PMIDs).
Fetched batch 190/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 191/317 (200 PMIDs).
Fetched batch 192/317 (200 PMIDs).
Fetched batch 193/317 (200 PMIDs).
Fetched batch 194/317 (200 PMIDs).
Fetched batch 195/317 (200 PMIDs).
Fetched batch 196/317 (200 PMIDs).
Fetched batch 197/317 (200 PMIDs).
Fetched batch 198/317 (200 PMIDs).
Fetched batch 199/317 (200 PMIDs).
Fetched batch 200/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 201/317 (200 PMIDs).
Fetched batch 202/317 (200 PMIDs).
Fetched batch 203/317 (200 PMIDs).
Fetched batch 204/317 (200 PMIDs).
Fetched batch 205/317 (200 PMIDs).
Fetched batch 206/317 (200 PMIDs).
Fetched batch 207/317 (200 PMIDs).
Fetched batch 208/317 (200 PMIDs).
Fetched batch 209/317 (200 PMIDs).
Fetched batch 210/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 211/317 (200 PMIDs).
Fetched batch 212/317 (200 PMIDs).
Fetched batch 213/317 (200 PMIDs).
Fetched batch 214/317 (200 PMIDs).
Fetched batch 215/317 (200 PMIDs).
Fetched batch 216/317 (200 PMIDs).
Fetched batch 217/317 (200 PMIDs).
Fetched batch 218/317 (200 PMIDs).
Fetched batch 219/317 (200 PMIDs).
Fetched batch 220/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 221/317 (200 PMIDs).
Fetched batch 222/317 (200 PMIDs).
Fetched batch 223/317 (200 PMIDs).
Fetched batch 224/317 (200 PMIDs).
Fetched batch 225/317 (200 PMIDs).
Fetched batch 226/317 (200 PMIDs).
Fetched batch 227/317 (200 PMIDs).
Fetched batch 228/317 (200 PMIDs).
Fetched batch 229/317 (200 PMIDs).
Fetched batch 230/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 231/317 (200 PMIDs).
Fetched batch 232/317 (200 PMIDs).
Fetched batch 233/317 (200 PMIDs).
Fetched batch 234/317 (200 PMIDs).
Fetched batch 235/317 (200 PMIDs).
Fetched batch 236/317 (200 PMIDs).
Fetched batch 237/317 (200 PMIDs).
Fetched batch 238/317 (200 PMIDs).
Fetched batch 239/317 (200 PMIDs).
Fetched batch 240/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 241/317 (200 PMIDs).
Fetched batch 242/317 (200 PMIDs).
Fetched batch 243/317 (200 PMIDs).
Fetched batch 244/317 (200 PMIDs).
Fetched batch 245/317 (200 PMIDs).
Fetched batch 246/317 (200 PMIDs).
Fetched batch 247/317 (200 PMIDs).
Fetched batch 248/317 (200 PMIDs).
Fetched batch 249/317 (200 PMIDs).
Fetched batch 250/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 251/317 (200 PMIDs).
Fetched batch 252/317 (200 PMIDs).
Fetched batch 253/317 (200 PMIDs).
Fetched batch 254/317 (200 PMIDs).
Fetched batch 255/317 (200 PMIDs).
Fetched batch 256/317 (200 PMIDs).
Fetched batch 257/317 (200 PMIDs).
Fetched batch 258/317 (200 PMIDs).
Fetched batch 259/317 (200 PMIDs).
Fetched batch 260/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 261/317 (200 PMIDs).
Fetched batch 262/317 (200 PMIDs).
Fetched batch 263/317 (200 PMIDs).
Fetched batch 264/317 (200 PMIDs).
Fetched batch 265/317 (200 PMIDs).
Fetched batch 266/317 (200 PMIDs).
Fetched batch 267/317 (200 PMIDs).
Fetched batch 268/317 (200 PMIDs).
Fetched batch 269/317 (200 PMIDs).
Fetched batch 270/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 271/317 (200 PMIDs).
Fetched batch 272/317 (200 PMIDs).
Fetched batch 273/317 (200 PMIDs).
Fetched batch 274/317 (200 PMIDs).
Fetched batch 275/317 (200 PMIDs).
Fetched batch 276/317 (200 PMIDs).
Fetched batch 277/317 (200 PMIDs).
Fetched batch 278/317 (200 PMIDs).
Fetched batch 279/317 (200 PMIDs).
Fetched batch 280/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 281/317 (200 PMIDs).
Fetched batch 282/317 (200 PMIDs).
Fetched batch 283/317 (200 PMIDs).
Fetched batch 284/317 (200 PMIDs).
Fetched batch 285/317 (200 PMIDs).
Fetched batch 286/317 (200 PMIDs).
Fetched batch 287/317 (200 PMIDs).
Fetched batch 288/317 (200 PMIDs).
Fetched batch 289/317 (200 PMIDs).
Fetched batch 290/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 291/317 (200 PMIDs).
Fetched batch 292/317 (200 PMIDs).
Fetched batch 293/317 (200 PMIDs).
Fetched batch 294/317 (200 PMIDs).
Fetched batch 295/317 (200 PMIDs).
Fetched batch 296/317 (200 PMIDs).
Fetched batch 297/317 (200 PMIDs).
Fetched batch 298/317 (200 PMIDs).
Fetched batch 299/317 (200 PMIDs).
Fetched batch 300/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 301/317 (200 PMIDs).
Fetched batch 302/317 (200 PMIDs).
Fetched batch 303/317 (200 PMIDs).
Fetched batch 304/317 (200 PMIDs).
Fetched batch 305/317 (200 PMIDs).
Fetched batch 306/317 (200 PMIDs).
Fetched batch 307/317 (200 PMIDs).
Fetched batch 308/317 (200 PMIDs).
Fetched batch 309/317 (200 PMIDs).
Fetched batch 310/317 (200 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.
Fetched batch 311/317 (200 PMIDs).
Fetched batch 312/317 (200 PMIDs).
Fetched batch 313/317 (200 PMIDs).
Fetched batch 314/317 (200 PMIDs).
Fetched batch 315/317 (200 PMIDs).
Fetched batch 316/317 (200 PMIDs).
Fetched batch 317/317 (116 PMIDs).
Checkpointed PubMed metadata cache to pubmed_pmid_metadata.parquet.

,pmid,pub_date,pub_year,venue
0,1000196,1976-11-01,1976,British medical journal
1,100029,1978-08-01,1978,The American review of respiratory disease
2,100050,1978-08-01,1978,Antimicrobial agents and chemotherapy
3,100051,1978-08-01,1978,Antimicrobial agents and chemotherapy
4,100194,1978-07-01,1978,Canadian journal of ophthalmology. Journal can...

## Save the pair-PMID association table

This table is the key bridge from interval-level search results to yearly AMR counts. Each row represents one positive PMID associated with one `(pathogen, antibiotic)` pair, now annotated with PubMed date metadata.

In [7]:
pair_pmid_enriched_df = attach_pubmed_metadata(pair_pmid_df, cache_df)
pair_pmid_enriched_df.to_parquet(PAIR_PMID_PATH, index=False)

print(f"saved pair-PMID associations to {PAIR_PMID_PATH}")
summarize_metadata_coverage(pair_pmid_enriched_df)

saved pair-PMID associations to pmids_results_positive_pair_pmid.parquet

                           metric   value
0                  pair_pmid_rows  154906
1                    unique_pmids   63316
2              rows_with_pub_year  154906
3           rows_missing_pub_year       0
4  rows_pub_year_matches_interval  154897
5  rows_pub_year_outside_interval       9

## Aggregate to yearly AMR counts

The yearly table below groups the enriched pair-PMID rows by publication year, giving a true annual count rather than a 5-year interval count.

In [8]:
yearly_df = aggregate_pair_counts_by_year(pair_pmid_enriched_df)
yearly_df.to_parquet(YEARLY_PATH, index=False)

print(f"saved yearly AMR counts to {YEARLY_PATH}")
print(f"yearly rows: {len(yearly_df):,}")

yearly_df.head()

saved yearly AMR counts to pmids_results_positive_yearly.parquet
yearly rows: 45,244

                pathogen     antibiotic  year  count       pmids
0  Abiotrophia defectiva       Cefepime  2016      1  [27216060]
1  Abiotrophia defectiva     Cefotaxime  2016      1  [27216060]
2  Abiotrophia defectiva    Ceftriaxone  2013      1  [24034902]
3  Abiotrophia defectiva  Ciprofloxacin  2013      1  [24034902]
4  Abiotrophia defectiva    Clindamycin  2000      1  [10681362]

## Quick diagnostics

This is a useful sanity check after the PubMed metadata pass. In most cases, a PMID should land inside the 5-year interval where it was originally found. Any rows outside that interval are worth reviewing.

In [9]:
diagnostics = summarize_metadata_coverage(pair_pmid_enriched_df)
diagnostics

pair_pmid_enriched_df.loc[
    pair_pmid_enriched_df["pub_year_matches_interval"] == False,
    ["pathogen", "antibiotic", "pmid", "pub_year", "start_date", "end_date", "venue"],
].head(20)

,pathogen,antibiotic,pmid,pub_year,start_date,end_date,venue
9531,Bordetella pertussis,Erythromycin,39313898,2025,2020/01/01,2024/12/31,Current pharmaceutical biotechnology
29470,Enterococcus gallinarum,Erythromycin,39046670,2025,2020/01/01,2024/12/31,Probiotics and antimicrobial proteins
37176,Escherichia coli,Cefotaxime,39461740,2026,2020/01/01,2024/12/31,BMJ military health
86027,Mycobacterium tuberculosis,Rifampicin,39058037,2025,2020/01/01,2024/12/31,Monaldi archives for chest disease = Archivio ...
135351,Staphylococcus aureus,Vancomycin,37886812,2026,2020/01/01,2024/12/31,The international journal of lower extremity w...
138961,Staphylococcus pseudintermedius,Amoxicillin,37855899,2026,2020/01/01,2024/12/31,"Microbial drug resistance (Larchmont, N.Y.)"
138969,Staphylococcus pseudintermedius,Amoxicillin/clavulanic-acid,37855899,2026,2020/01/01,2024/12/31,"Microbial drug resistance (Larchmont, N.Y.)"
138994,Staphylococcus pseudintermedius,Cefazolin,37855899,2026,2020/01/01,2024/12/31,"Microbial drug resistance (Larchmont, N.Y.)"
139372,Staphylococcus pseudintermedius,Tetracycline,37855899,2026,2020/01/01,2024/12/31,"Microbial drug resistance (Larchmont, N.Y.)"